"""Tests for the SVG optimisation engine."""

from __future__ import annotations

import xml.etree.ElementTree as ET

import pytest

from pidraw.optimizer.svg_optimizer import (
    DEFAULT_PASSES,
    PASS_REGISTRY,
    OptimizationResult,
    optimize_many,
    optimize_svg,
)
from pidraw.optimizer.validators import SVGValidationError, validate_svg

# ---------------------------------------------------------------------------
# Sample SVGs for testing
# ---------------------------------------------------------------------------

MINIMAL_SVG = '<svg xmlns="http://www.w3.org/2000/svg"><rect width="100" height="100"/></svg>'

SVG_WITH_COMMENTS = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <!-- this is a comment -->
  <rect width="100" height="100"/>
  <!-- another comment -->
</svg>"""

SVG_WITH_EDITOR_META = """\
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd">
  <sodipodi:namedview id="namedview1" pagecolor="#ffffff"/>
  <metadata><rdf>some editor data</rdf></metadata>
  <rect width="100" height="100" inkscape:label="rect1"/>
</svg>"""

SVG_WITH_UNUSED_DEFS = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="used"><stop offset="0%" stop-color="red"/></linearGradient>
    <linearGradient id="unused"><stop offset="0%" stop-color="blue"/></linearGradient>
    <linearGradient id="also-unused"><stop offset="0%" stop-color="green"/></linearGradient>
  </defs>
  <rect width="100" height="100" fill="url(#used)"/>
</svg>"""

SVG_WITH_DUPLICATE_DEFS = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="a" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="red"/>
      <stop offset="100%" stop-color="blue"/>
    </linearGradient>
    <linearGradient id="b" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="red"/>
      <stop offset="100%" stop-color="blue"/>
    </linearGradient>
  </defs>
  <rect width="100" height="100" fill="url(#a)"/>
</svg>"""

SVG_WITH_REDUNDANT_GROUPS = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <g>
    <g>
      <rect width="50" height="50"/>
    </g>
  </g>
</svg>"""

SVG_WITH_EMPTY_ELEMENTS = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <g></g>
  <rect width="100" height="100"/>
  <g id="keep-me"/>
</svg>"""

SVG_WITH_TRANSFORMS = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <g transform="  Translate (10,  20) scale(2, 3) ">
    <rect width="100" height="100"/>
  </g>
</svg>"""

SVG_WITH_PATHS = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <path d="M 10.0 20.0 L 30.0 40.0 C 50.0 60.0 70.0 80.0 90.0 100.0"/>
</svg>"""

SVG_WHITESPACE_HEAVY = """\
<svg   xmlns="http://www.w3.org/2000/svg"   >
  <rect   width="100"   height="100"   />
</svg>"""

SVG_ATTRIBUTE_ORDER = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <rect height="50" width="100" y="10" x="20" id="r1"/>
</svg>"""

SVG_LARGE = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <rect width="100" height="100" fill="red"/>
  <circle cx="50" cy="50" r="30" fill="blue" opacity="0.5"/>
  <text x="10" y="20" font-family="Arial" font-size="14">Hello</text>
  <g transform="translate(10, 10)">
    <path d="M 0 0 L 10 10 L 20 0 Z"/>
  </g>
  <defs>
    <linearGradient id="g1"><stop offset="0%" stop-color="#fff"/></linearGradient>
  </defs>
  <rect width="200" height="200" fill="url(#g1)"/>
</svg>"""

# Representative SVGs mimicing different renderer styles

MERMAID_LIKE_SVG = """\
<svg xmlns="http://www.w3.org/2000/svg" id="mermaid-svg" viewBox="0 0 200 200">
  <!-- Diagram generated by Mermaid -->
  <defs>
    <marker id="arrowhead" viewBox="0 0 10 10" refX="10" refY="5"
            markerWidth="6" markerHeight="6" orient="auto">
      <path d="M 0 0 L 10 5 L 0 10 Z"/>
    </marker>
  </defs>
  <g>
    <rect class="node" x="10" y="10" width="80" height="40"/>
    <text x="50" y="35" text-anchor="middle">Start</text>
  </g>
</svg>"""

GRAPHVIZ_LIKE_SVG = """\
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd">
  <!-- generated by Graphviz  -->
  <sodipodi:namedview id="base" pagecolor="#ffffff"/>
  <g id="graph0" class="graph">
    <g id="node1" class="node">
      <title>A</title>
      <ellipse cx="50" cy="50" rx="30" ry="20"/>
      <text x="50" y="55" text-anchor="middle">A</text>
    </g>
    <g id="node2" class="node">
      <title>B</title>
      <ellipse cx="150" cy="50" rx="30" ry="20"/>
      <text x="150" y="55" text-anchor="middle">B</text>
    </g>
    <g id="edge1" class="edge">
      <path d="M 80 50 C 100 50 100 50 120 50" fill="none" stroke="black"/>
      <polygon points="120 50 110 45 110 55" fill="black"/>
    </g>
  </g>
</svg>"""

PLANTUML_LIKE_SVG = """\
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- PlantUML generated -->
  <defs>
    <linearGradient id="a" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#FEFEFE"/>
      <stop offset="1" stop-color="#EEEEEE"/>
    </linearGradient>
    <linearGradient id="b" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#FEFEFE"/>
      <stop offset="1" stop-color="#EEEEEE"/>
    </linearGradient>
  </defs>
  <g id="Alice">
    <rect width="80" height="40" fill="url(#a)" stroke="black"/>
    <text x="40" y="25" text-anchor="middle">Alice</text>
  </g>
</svg>"""

D2_LIKE_SVG = """\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 300">
  <defs>
    <marker id="mk" viewBox="0 0 10 10" refX="10" refY="5">
      <path d="M 0 0 L 10 5 L 0 10 Z"/>
    </marker>
    <marker id="mk-dup" viewBox="0 0 10 10" refX="10" refY="5">
      <path d="M 0 0 L 10 5 L 0 10 Z"/>
    </marker>
  </defs>
  <!-- d2 diagram -->
  <g>
    <g>
      <rect class="shape" x="10" y="10" width="100" height="50"/>
      <text x="60" y="40" text-anchor="middle">hello</text>
    </g>
    <g>
      <path d="M 120 35 C 140 35 160 35 180 35" stroke="black"/>
      <polygon points="180 35 170 30 170 40"/>
    </g>
  </g>
</svg>"""

ASCII_LIKE_SVG = """\
<svg xmlns="http://www.w3.org/2000/svg">
  <g>
    <g>
      <g>
        <text x="10" y="20">+---+</text>
        <text x="10" y="35">| A |</text>
        <text x="10" y="50">+---+</text>
      </g>
    </g>
  </g>
</svg>"""


# ===================================================================
# Validation
# ===================================================================


class TestValidation:
    def test_valid_minimal_svg(self) -> None:
        assert validate_svg(MINIMAL_SVG) is True

    def test_empty_string_raises(self) -> None:
        with pytest.raises(SVGValidationError, match="empty"):
            validate_svg("")

    def test_whitespace_only_raises(self) -> None:
        with pytest.raises(SVGValidationError, match="empty"):
            validate_svg("   \n  ")

    def test_no_svg_root_raises(self) -> None:
        with pytest.raises(SVGValidationError, match="<svg>"):
            validate_svg("<div></div>")

    def test_malformed_xml_raises(self) -> None:
        with pytest.raises(SVGValidationError, match="XML parsing"):
            validate_svg("<svg><unclosed>")

    def test_svg_with_declaration(self) -> None:
        svg = '<?xml version="1.0"?>\n<svg xmlns="http://www.w3.org/2000/svg"/>'
        assert validate_svg(svg) is True


# ===================================================================
# Individual passes
# ===================================================================


class TestRemoveComments:
    def test_removes_single_comment(self) -> None:
        result = optimize_svg(SVG_WITH_COMMENTS, passes=["remove_comments"])
        assert "<!--" not in result.svg
        assert "comment" not in result.svg

    def test_does_not_remove_text_content(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><text>&lt;!-- not a comment --></text></svg>'
        result = optimize_svg(svg, passes=["remove_comments"])
        assert "text" in result.svg

    def test_svg_still_valid(self) -> None:
        result = optimize_svg(SVG_WITH_COMMENTS, passes=["remove_comments"])
        validate_svg(result.svg)

    def test_removes_multiline_comments(self) -> None:
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg">'
            "<!--\nmulti\nline\n-->"
            '<rect width="10" height="10"/></svg>'
        )
        result = optimize_svg(svg, passes=["remove_comments"])
        assert "<!--" not in result.svg
        assert "multi" not in result.svg


class TestRemoveEditorMetadata:
    def test_removes_inkscape_attrs(self) -> None:
        result = optimize_svg(SVG_WITH_EDITOR_META, passes=["remove_editor_metadata"])
        assert "inkscape:label" not in result.svg

    def test_removes_sodipodi_namedview(self) -> None:
        result = optimize_svg(SVG_WITH_EDITOR_META, passes=["remove_editor_metadata"])
        assert "sodipodi:namedview" not in result.svg

    def test_removes_metadata_block(self) -> None:
        result = optimize_svg(SVG_WITH_EDITOR_META, passes=["remove_editor_metadata"])
        assert "<metadata>" not in result.svg

    def test_preserves_svg_structure(self) -> None:
        result = optimize_svg(SVG_WITH_EDITOR_META, passes=["remove_editor_metadata"])
        validate_svg(result.svg)


class TestRemoveUnusedDefs:
    def test_removes_unreferenced_defs(self) -> None:
        result = optimize_svg(SVG_WITH_UNUSED_DEFS, passes=["remove_unused_defs"])
        assert "unused" not in result.svg
        assert "also-unused" not in result.svg

    def test_keeps_referenced_defs(self) -> None:
        result = optimize_svg(SVG_WITH_UNUSED_DEFS, passes=["remove_unused_defs"])
        assert "used" in result.svg

    def test_no_defs_returns_unchanged(self) -> None:
        result = optimize_svg(MINIMAL_SVG, passes=["remove_unused_defs"])
        validate_svg(result.svg)
        assert "rect" in result.svg

    def test_preserves_href_references(self) -> None:
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg">'
            '<defs><circle id="c1" r="5"/></defs>'
            '<use href="#c1"/></svg>'
        )
        result = optimize_svg(svg, passes=["remove_unused_defs"])
        assert "c1" in result.svg

    def test_preserves_url_references(self) -> None:
        result = optimize_svg(SVG_WITH_UNUSED_DEFS, passes=["remove_unused_defs"])
        assert "url(#used)" in result.svg


class TestMergeDuplicateDefs:
    def test_merges_identical_defs(self) -> None:
        result = optimize_svg(SVG_WITH_DUPLICATE_DEFS, passes=["merge_duplicate_defs"])
        root = ET.fromstring(result.svg)
        defs = root.findall(".//{http://www.w3.org/2000/svg}linearGradient")
        assert len(defs) == 1

    def test_keeps_reference_working(self) -> None:
        result = optimize_svg(SVG_WITH_DUPLICATE_DEFS, passes=["merge_duplicate_defs"])
        assert "url(#a)" in result.svg


class TestCollapseRedundantGroups:
    def test_collapses_nested_groups(self) -> None:
        result = optimize_svg(SVG_WITH_REDUNDANT_GROUPS, passes=["collapse_redundant_groups"])
        root = ET.fromstring(result.svg)
        groups = list(root.iter("{http://www.w3.org/2000/svg}g"))
        assert len(groups) == 0

    def test_preserves_visible_content(self) -> None:
        result = optimize_svg(SVG_WITH_REDUNDANT_GROUPS, passes=["collapse_redundant_groups"])
        assert "rect" in result.svg

    def test_does_not_collapse_group_with_id(self) -> None:
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg">'
            '<g id="keep"><rect width="10" height="10"/></g></svg>'
        )
        result = optimize_svg(svg, passes=["collapse_redundant_groups"])
        assert 'id="keep"' in result.svg


class TestRemoveEmptyElements:
    def test_removes_empty_group(self) -> None:
        result = optimize_svg(SVG_WITH_EMPTY_ELEMENTS, passes=["remove_empty_elements"])
        assert "<g></g>" not in result.svg

    def test_preserves_group_with_id(self) -> None:
        result = optimize_svg(SVG_WITH_EMPTY_ELEMENTS, passes=["remove_empty_elements"])
        assert 'id="keep-me"' in result.svg

    def test_preserves_visible_elements(self) -> None:
        result = optimize_svg(SVG_WITH_EMPTY_ELEMENTS, passes=["remove_empty_elements"])
        assert "rect" in result.svg
        assert 'width="100"' in result.svg

    def test_preserves_element_with_class(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><rect class="spacer" /></svg>'
        result = optimize_svg(svg, passes=["remove_empty_elements"])
        assert 'class="spacer"' in result.svg

    def test_preserves_element_with_data_attr(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><circle data-tooltip="info" /></svg>'
        result = optimize_svg(svg, passes=["remove_empty_elements"])
        assert 'data-tooltip="info"' in result.svg

    def test_preserves_element_with_role_and_event(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><g role="button" tabindex="0" onclick="submit()" /></svg>'
        result = optimize_svg(svg, passes=["remove_empty_elements"])
        assert 'role="button"' in result.svg
        assert 'tabindex="0"' in result.svg
        assert "onclick" in result.svg

    def test_preserves_zero_dim_with_data_attr(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><rect width="0" height="0" data-target="zone" /></svg>'
        result = optimize_svg(svg, passes=["remove_empty_elements"])
        assert 'data-target="zone"' in result.svg

    def test_preserves_element_with_aria_label(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><g aria-label="description" /></svg>'
        result = optimize_svg(svg, passes=["remove_empty_elements"])
        assert 'aria-label="description"' in result.svg

    def test_preserves_element_with_style(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><polygon style="display:none" /></svg>'
        result = optimize_svg(svg, passes=["remove_empty_elements"])
        assert 'style="display:none"' in result.svg

    def test_strips_truly_bare_elements(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><rect /><g></g><circle></circle></svg>'
        result = optimize_svg(svg, passes=["remove_empty_elements"])
        assert "<rect" not in result.svg
        assert "<g>" not in result.svg
        assert "<circle" not in result.svg


class TestNormalizeTransforms:
    def test_normalizes_spacing(self) -> None:
        result = optimize_svg(SVG_WITH_TRANSFORMS, passes=["normalize_transforms"])
        root = ET.fromstring(result.svg)
        ns = "{http://www.w3.org/2000/svg}"
        g = root.find(f".//{ns}g")
        assert g is not None
        t = g.get("transform", "")
        assert "  " not in t
        assert "Translate" not in t

    def test_canonical_form(self) -> None:
        result = optimize_svg(SVG_WITH_TRANSFORMS, passes=["normalize_transforms"])
        assert "translate(10, 20)" in result.svg
        assert "scale(2, 3)" in result.svg


class TestSimplifyPaths:
    def test_removes_trailing_zeros(self) -> None:
        result = optimize_svg(SVG_WITH_PATHS, passes=["simplify_paths"])
        assert "10.0" not in result.svg.split("M")[1]
        assert "10" in result.svg

    def test_preserves_path_structure(self) -> None:
        result = optimize_svg(SVG_WITH_PATHS, passes=["simplify_paths"])
        assert "M" in result.svg
        assert "C" in result.svg
        assert "L" in result.svg


class TestTrimWhitespace:
    def test_collapses_extra_space(self) -> None:
        result = optimize_svg(SVG_WHITESPACE_HEAVY, passes=["trim_whitespace"])
        assert "  " not in result.svg

    def test_preserves_text_content(self) -> None:
        svg = '<svg xmlns="http://www.w3.org/2000/svg"><text>hello world</text></svg>'
        result = optimize_svg(svg, passes=["trim_whitespace"])
        assert "hello world" in result.svg

    def test_valid_output(self) -> None:
        result = optimize_svg(SVG_WHITESPACE_HEAVY, passes=["trim_whitespace"])
        validate_svg(result.svg)


class TestNormalizeAttributeOrdering:
    def test_id_first(self) -> None:
        result = optimize_svg(SVG_ATTRIBUTE_ORDER, passes=["normalize_attribute_ordering"])
        pos_id = result.svg.index('id="r1"')
        pos_x = result.svg.index('x="20"')
        assert pos_id < pos_x

    def test_deterministic_output(self) -> None:
        r1 = optimize_svg(SVG_ATTRIBUTE_ORDER, passes=["normalize_attribute_ordering"])
        r2 = optimize_svg(SVG_ATTRIBUTE_ORDER, passes=["normalize_attribute_ordering"])
        assert r1.svg == r2.svg


# ===================================================================
# Full pipeline
# ===================================================================


class TestFullPipeline:
    def test_minimal_svg(self) -> None:
        result = optimize_svg(MINIMAL_SVG)
        validate_svg(result.svg)

    def test_all_passes_applied(self) -> None:
        result = optimize_svg(MERMAID_LIKE_SVG)
        for name in DEFAULT_PASSES:
            assert name in result.passes_applied

    def test_svg_structure_preserved(self) -> None:
        result = optimize_svg(SVG_LARGE)
        validate_svg(result.svg)
        root = ET.fromstring(result.svg)
        assert root.tag.endswith("svg")

    def test_text_preserved(self) -> None:
        result = optimize_svg(SVG_LARGE)
        assert "Hello" in result.svg

    def test_paths_preserved(self) -> None:
        result = optimize_svg(SVG_LARGE)
        assert "L" in result.svg or "M" in result.svg

    def test_content_ordering(self) -> None:
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg">'
            '<rect width="10" height="10"/>'
            '<circle cx="5" cy="5" r="5"/></svg>'
        )
        result = optimize_svg(svg)
        validate_svg(result.svg)
        assert "<rect" in result.svg
        assert "<circle" in result.svg


# ===================================================================
# Metrics
# ===================================================================


class TestMetrics:
    def test_original_size(self) -> None:
        result = optimize_svg(MINIMAL_SVG)
        assert result.original_size > 0

    def test_optimized_size(self) -> None:
        result = optimize_svg(MINIMAL_SVG)
        assert result.optimized_size > 0

    def test_bytes_saved(self) -> None:
        result = optimize_svg(SVG_WITH_COMMENTS)
        assert result.bytes_saved > 0

    def test_reduction_percent(self) -> None:
        result = optimize_svg(SVG_WITH_COMMENTS)
        assert result.reduction_percent > 0
        assert result.reduction_percent <= 100.0

    def test_ratio(self) -> None:
        result = optimize_svg(SVG_WITH_COMMENTS)
        assert 0 <= result.ratio <= 1

    def result_fields_not_empty(self) -> None:
        result = optimize_svg(MINIMAL_SVG)
        assert isinstance(result.svg, str)
        assert len(result.svg) > 0
        assert result.elapsed_ms >= 0

    def test_result_is_dataclass(self) -> None:
        result = optimize_svg(MINIMAL_SVG)
        assert isinstance(result, OptimizationResult)


# ===================================================================
# Batch optimisation
# ===================================================================


class TestOptimizeMany:
    def test_batch_returns_list(self) -> None:
        results = optimize_many([MINIMAL_SVG, SVG_WITH_COMMENTS])
        assert isinstance(results, list)
        assert len(results) == 2

    def test_each_result_is_valid(self) -> None:
        results = optimize_many([MINIMAL_SVG, SVG_WITH_COMMENTS])
        for r in results:
            assert isinstance(r, OptimizationResult)
            validate_svg(r.svg)

    def tests_empty_input(self) -> None:
        results = optimize_many([])
        assert results == []

    def test_each_svg_independent(self) -> None:
        results = optimize_many([SVG_WITH_COMMENTS, MINIMAL_SVG])
        assert "<!--" not in results[0].svg
        validate_svg(results[1].svg)


# ===================================================================
# Renderer-specific SVG integration
# ===================================================================


class TestMermaidLikeSVG:
    def test_valid_output(self) -> None:
        result = optimize_svg(MERMAID_LIKE_SVG)
        validate_svg(result.svg)

    def test_text_preserved(self) -> None:
        result = optimize_svg(MERMAID_LIKE_SVG)
        assert "Start" in result.svg

    def test_size_reduced(self) -> None:
        result = optimize_svg(MERMAID_LIKE_SVG)
        assert result.bytes_saved > 0


class TestGraphvizLikeSVG:
    def test_valid_output(self) -> None:
        result = optimize_svg(GRAPHVIZ_LIKE_SVG)
        validate_svg(result.svg)

    def test_editor_meta_removed(self) -> None:
        result = optimize_svg(GRAPHVIZ_LIKE_SVG)
        assert "inkscape" not in result.svg
        assert "sodipodi" not in result.svg

    def test_graph_structure_preserved(self) -> None:
        result = optimize_svg(GRAPHVIZ_LIKE_SVG)
        assert "graph0" in result.svg or "graph" in result.svg
        assert "A" in result.svg
        assert "B" in result.svg


class TestPlantUMLLikeSVG:
    def test_valid_output(self) -> None:
        result = optimize_svg(PLANTUML_LIKE_SVG)
        validate_svg(result.svg)

    def test_duplicate_defs_merged(self) -> None:
        result = optimize_svg(PLANTUML_LIKE_SVG)
        root = ET.fromstring(result.svg)
        ns = "{http://www.w3.org/2000/svg}"
        grads = root.findall(f".//{ns}linearGradient")
        assert len(grads) <= 1

    def test_text_preserved(self) -> None:
        result = optimize_svg(PLANTUML_LIKE_SVG)
        assert "Alice" in result.svg


class TestD2LikeSVG:
    def test_valid_output(self) -> None:
        result = optimize_svg(D2_LIKE_SVG)
        validate_svg(result.svg)

    def test_duplicate_markers_merged(self) -> None:
        result = optimize_svg(D2_LIKE_SVG)
        assert "mk-dup" not in result.svg

    def test_groups_collapsed(self) -> None:
        result = optimize_svg(D2_LIKE_SVG)
        root = ET.fromstring(result.svg)
        ns = "{http://www.w3.org/2000/svg}"
        groups = list(root.iter(f"{ns}g"))
        assert len(groups) <= 3

    def test_text_preserved(self) -> None:
        result = optimize_svg(D2_LIKE_SVG)
        assert "hello" in result.svg


class TestASCIILikeSVG:
    def test_valid_output(self) -> None:
        result = optimize_svg(ASCII_LIKE_SVG)
        validate_svg(result.svg)

    def test_groups_collapsed(self) -> None:
        result = optimize_svg(ASCII_LIKE_SVG)
        root = ET.fromstring(result.svg)
        ns = "{http://www.w3.org/2000/svg}"
        groups = list(root.iter(f"{ns}g"))
        assert len(groups) <= 1

    def test_text_preserved(self) -> None:
        result = optimize_svg(ASCII_LIKE_SVG)
        assert "+---+" in result.svg
        assert "| A |" in result.svg


# ===================================================================
# Safety: verify that optimisation never removes visible content
# ===================================================================


class TestSafety:
    def test_root_element_preserved(self) -> None:
        result = optimize_svg(MINIMAL_SVG)
        assert result.svg.strip().startswith("<svg")

    def test_visible_elements_preserved(self) -> None:
        result = optimize_svg(SVG_LARGE)
        assert "<rect" in result.svg
        assert "<circle" in result.svg

    def test_text_node_preserved(self) -> None:
        result = optimize_svg(SVG_LARGE)
        assert "Hello" in result.svg

    def test_style_preserved(self) -> None:
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg">'
            "<style>.red{fill:red;}</style>"
            '<rect class="red" width="10" height="10"/></svg>'
        )
        result = optimize_svg(svg, passes=[p for p in DEFAULT_PASSES if p != "trim_whitespace"])
        assert ".red" in result.svg

    def test_well_formed_after_optimization(self) -> None:
        result = optimize_svg(SVG_LARGE)
        ET.fromstring(result.svg)


# ===================================================================
# Edge cases
# ===================================================================


class TestEdgeCases:
    def test_optimize_empty_string_raises(self) -> None:
        with pytest.raises(SVGValidationError):
            optimize_svg("")

    def test_optimize_invalid_xml_raises(self) -> None:
        with pytest.raises(SVGValidationError):
            optimize_svg("<svg><unclosed>")

    def test_unknown_pass_raises(self) -> None:
        with pytest.raises(ValueError, match="Unknown pass"):
            optimize_svg(MINIMAL_SVG, passes=["nonexistent_pass"])

    def test_custom_pass_function(self) -> None:
        def uppercase(s: str) -> str:
            return s.upper()

        result = optimize_svg(MINIMAL_SVG, passes=[uppercase])
        assert "SVG" in result.svg

    def test_skip_validation(self) -> None:
        result = optimize_svg(MINIMAL_SVG, validate_input=False, validate_output=False)
        assert result.optimized_size > 0

    def test_svg_with_text_span(self) -> None:
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg">'
            '<text>hello <tspan font-weight="bold">world</tspan></text></svg>'
        )
        result = optimize_svg(svg)
        validate_svg(result.svg)
        assert "hello" in result.svg
        assert "world" in result.svg

    def test_svg_with_declarations(self) -> None:
        svg = (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
            '"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n'
            '<svg xmlns="http://www.w3.org/2000/svg">'
            '<rect width="10" height="10"/></svg>'
        )
        result = optimize_svg(svg, validate_input=True)
        validate_svg(result.svg)

    def test_pass_registry_completeness(self) -> None:
        assert set(DEFAULT_PASSES) == set(PASS_REGISTRY.keys())
        assert len(PASS_REGISTRY) == 10

    def test_namespace_handling_without_ns(self) -> None:
        svg = "<svg><rect width='10' height='10'/></svg>"
        result = optimize_svg(svg)
        validate_svg(result.svg)
